services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  publisher-api:
    build:
      context: ./
      dockerfile: "src/Acme.PublisherApi/Dockerfile"
    image: "acme.publisherapi:dev"
    ports:
      - "5001:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"

  consumer-api:
    build:
      context: ./
      dockerfile: "src/Acme.ConsumerApi/Dockerfile"
    image: "acme.consumerapi:dev"
    ports:
      - "5002:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
